### ISSUE TITLE
Is there the source available to compile on old kernel ?

### ISSUE THREAD

**Issue by girpierr** [grimme-lab/xtbiff#2]
Dear developpers,

I tried to run the xtbiff binary on a cluster but the kernel of the server is too old, so I donwloaded the source.zip in order to compile a relevant binary for this kernel but there is only the README.md file in it. 
Thanks and best regards
Pierre

**Comment by cplett** [comment]
Hi,
Unfortunately, the source code is currently not open source. Therefore, compiling the xtbiff is currently not possible.
However, we are working on implementing this into the xtb program, which will be available also as source code of xtb in a future release.

**Comment by girpierr** [comment]
Dear Christoph,
Thank you for your fast reply. No big deal, I will try on another cluster with a more recent kernel and wait for the future xtb release to install on old cluster.
Thank you again.
Pierre
