### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by glagovsky** [grimme-lab/xtbiff#4]
Hi,

I'm trying to use QCG via crest on Linux server and I am getting SIGSEGV/SIGABRT errors (screenshot attached).
I can see that xtbiff runs for some time and then stops.
Xtb (6.6.1) and crest (2.12) without QCG are working perfectly.

From xtb_opt.out file located in tmp_grow:

########################################################################
[WARNING] Runtime exception occurred
-1- gfnff_setup: Could not read topology file.
########################################################################

The server is running CentOS Linux 7 (Core), Kernel: Linux 3.10.0-1160.95.1.el7.x86_64

output from terminal:
[log1.txt](https://github.com/grimme-lab/xtbiff/files/14215176/log1.txt)
[log2.txt](https://github.com/grimme-lab/xtbiff/files/14215177/log2.txt)

![xtbiff_error](https://github.com/grimme-lab/xtbiff/assets/159487065/89bb796e-2cfa-4bc2-be5c-9ca72f6dcf7b)

Thanks in advance,
Yuri

**Comment by cplett** [comment]
Hi Yuri,
in `crest` 2.12 there was a problem with the QCG. If you have the possibility, I would suggest to try a `crest` version compiled from the current source code or version 2.11.2.

**Comment by glagovsky** [comment]
Thanks, I've tried the precompiled latest pre-release version (2719412) and it worked (only with one processor, though).
